# Generated by Django 5.0.1 on 2024-02-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='is_teacher'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacherDesignation',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='teacherDesignation'),
        ),
    ]
