# Generated by Django 5.0.1 on 2024-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_teacher_user_teacherdesignation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PrevYearRoll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='currentYearRoll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='is_student'),
        ),
        migrations.AddField(
            model_name='user',
            name='studCurrentYear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='studPrevYear',
            field=models.IntegerField(default=0),
        ),
    ]
