# Generated by Django 5.0.1 on 2024-02-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_prevyearroll_user_currentyearroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='section'),
        ),
    ]
