# Generated by Django 5.0.1 on 2024-02-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloodGroup',
            field=models.CharField(default='', max_length=30, verbose_name='bloodGroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=30, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherMobile',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='fatherMobile'),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherNID',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='fatherNID'),
        ),
        migrations.AddField(
            model_name='user',
            name='fatherProf',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='fatherProf'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(default='', max_length=30, verbose_name='group'),
        ),
        migrations.AddField(
            model_name='user',
            name='motherMobile',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='motherMobile'),
        ),
        migrations.AddField(
            model_name='user',
            name='motherNID',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='motherNID'),
        ),
        migrations.AddField(
            model_name='user',
            name='motherProf',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='motherProf'),
        ),
        migrations.AddField(
            model_name='user',
            name='optionalSubject',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='optionalSubject'),
        ),
        migrations.AddField(
            model_name='user',
            name='remarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='studID',
            field=models.CharField(default='', max_length=30, verbose_name='studID'),
        ),
    ]
